version: 2
updates:
  # Project level updates.
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    reviewers:
      - "MarioValdezDev"

  # App Module level updates.
  - package-ecosystem: gradle
    directory: "/app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    reviewers:
      - "MarioValdezDev"
